name: Idvogados
title: Idvogados
description: Projeto de acesso à Justiça.
tags:
  - Idvogados
  - Justiça
  - Advogados
  - Entregadores
  - Trabalhadores
  - GregNews
link-anchor:
  - title: Home
    url: /
  - title: Blog
    url: /blog/
link-button:
  - title: Quero Colaborar
    url: https://linktr.ee/idvogados
link-footer:
  - title: Termos de Uso
    url: /termos-de-uso/
  - title: Imprint
    action: window.print()
  - title: RSS
    url: /feed.xml
# email: contato@idvogados.org
email: parceiro.idvogados@gmail.com
disqus_username: idvogados
copyright-year: 2020
