name: Idvogados
title: Idvogados
description: Projeto de acesso à justiça.
tags:
  - Idvogados
  - Justiça
  - Advogados
  - Entregadores
  - Trabalhadores
  - GregNews
link-anchor:
  - title: Home
    url: /
  - title: Se informe
    url: /blog/
  - title: Colabore
    url: /colabore/
link-button:
  - title: Ajuda Profissional
    url: /pergunte/
link-footer:
  - title: Termos de Uso
    url: /termos-de-uso/
  - title: Imprint
    action: window.print()
  - title: RSS
    url: /feed.xml
email: idvogados@outlook.com
disqus_username: idvogados
copyright-year: 2020
