backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
collections:
  - label: "Categorias"
    name: "categories"
    folder: "category"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    preview_path: "category/{{slug}}"
    extension: "md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "category"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Slug"
        name: "slug"
        widget: "hidden"
        default: "{{slug}}"
      - label: "Descrição"
        name: "description"
        widget: "string"
        required: false
  - label: "Postagens"
    name: "posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    extension: "md"
    fields:
      - label: "Data da Publicação"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Subtítulo"
        name: "subtitle"
        widget: "string"
        required: false
      - label: "Descrição"
        name: "description"
        hint: "Isso será usado nas páginas e nos mecanismos de pesquisa."
        widget: "string"
      - label: "Categoria"
        name: "category"
        widget: "relation"
        collection: "categories"
        searchFields: ["title"]
        valueField: "slug"
        displayFields: ["title"]
      - label: "Tags"
        name: "tags"
        hint: "Separe com vírgulas. Eles também serão usados como palavras-chave para os mecanismos de pesquisa."
        widget: "list"
      - label: "Autor"
        name: "author"
        widget: "relation"
        collection: "authors"
        displayFields: [display_name]
        searchFields: [display_name]
        valueField: "name"
      - label: "Texto"
        name: "body"
        widget: "markdown"
  - label: "Páginas"
    name: "pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    extension: "md"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "page"
      - label: "Mostrar no Menu"
        name: "menu"
        widget: "boolean"
        default: true
      - label: "Data de Publicação"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD HH:mm:ss"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "hidden"
        default: "/{{slug}}/"
      - label: "Descrição"
        name: "description"
        hint: "Isso será usado como descrição para os mecanismos de pesquisa."
        widget: "string"
        required: false
      - label: "Keywords"
        name: "tags"
        hint: "Separe com vírgulas. Eles também serão usados como palavras-chave para os mecanismos de pesquisa."
        widget: "list"
        required: false
      - label: "Texto"
        name: "body"
        widget: "markdown"
  - label: "Autores"
    name: "authors"
    folder: "_authors/"
    create: true
    editor:
      preview: false
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "author"
      - label: "Foto"
        name: "photo"
        widget: "image"
        required: false
        hint: "Use uma imagem quadrada"
      - label: "Nome Curto"
        name: "name"
        widget: "string"
      - label: "Nome Exibido"
        name: "display_name"
        widget: "string"
      - label: "Bio"
        name: "bio"
        widget: "text"
      - label: "GitHub"
        name: "github_username"
        hit: "Apenas o username"
        widget: "string"
        required: false
      - label: "Facebook"
        name: "facebook_username"
        hit: "Apenas o username"
        widget: "string"
        required: false
      - label: "Twitter"
        name: "twitter_username"
        hit: "Apenas o username"
        widget: "string"
        required: false
      - label: "Instagram"
        name: "instagram_username"
        hit: "Apenas o username"
        widget: "string"
        required: false
      - label: "LinkedIn"
        name: "linkedin_username"
        hit: "Apenas o username"
        widget: "string"
        required: false
      - label: "Medium"
        name: "medium_username"
        hit: "Apenas o username"
        widget: "string"
        required: false
  - label: "Configurações"
    name: "settings"
    editor:
      preview: false
    delete: false
    files:
      - label: "Site"
        name: "site"
        file: "src/yml/site.yml"
        fields:
          - label: "Nome"
            name: "name"
          - label: "Título"
            name: "title"
            widget: "string"
          - label: "Descrição"
            name: "description"
            widget: "string"
            hint: "Isso será usado como descrição para os mecanismos de pesquisa."
          - label: "Keywords"
            name: "tags"
            hint: "Separe com vírgulas. Eles também serão usados como palavras-chave para os mecanismos de pesquisa."
            widget: "list"
            required: false
          - label: "Links do Cabeçalho (anchor)"
            name: "link-anchor"
            widget: "list"
            required: false
            fields:
              - label: "Título"
                name: "title"
                widget: "string"
                hint: "Texto que aparecerá"
              - label: "URL"
                name: "url"
                widget: "string"
                hint: "Ex: /blog"
          - label: "Menu no Cabeçalho (button)"
            name: "link-button"
            widget: "list"
            required: false
            fields:
              - label: "Título"
                name: "title"
                widget: "string"
                hint: "Texto que aparecerá"
              - label: "URL"
                name: "url"
                widget: "string"
                hint: "Ex: /blog"
          - label: "Menu no Rodapé"
            name: "link-footer"
            widget: "list"
            required: false
            fields:
              - label: "Título"
                name: "title"
                widget: "string"
                hint: "Texto que aparecerá no menu"
              - label: "URL"
                name: "url"
                widget: "string"
                hint: "Ex: /blog"
                required: false
              - label: "Ação"
                name: "action"
                widget: "string"
                hint: "Código em JS"
                required: false
          - label: "E-mail"
            name: "email"
            widget: "string"
          - label: "Disqus"
            name: "disqus_username"
            widget: "string"
            hint: "Deixe em branco se não quiser comentários nas postagens"
            required: false
          - label: "Ano do Copyright"
            name: "copyright-year"
            widget: "number"
      - label: "Social"
        name: "social"
        file: "src/yml/social.yml"
        fields:
          - label: "GitHub"
            name: "github_username"
            widget: "string"
            hit: "Apenas o username"
            required: false
          - label: "Facebook"
            name: "facebook_username"
            widget: "string"
            hit: "Apenas o username"
            required: false
          - label: "Twitter"
            name: "twitter_username"
            widget: "string"
            hit: "Apenas o username"
            required: false
          - label: "Instagram"
            name: "instagram_username"
            widget: "string"
            hit: "Apenas o username"
            required: false
          - label: "LinkedIn"
            name: "linkedin_username"
            widget: "string"
            hit: "Apenas o username"
            required: false
          - label: "Medium"
            name: "medium_username"
            widget: "string"
            hit: "Apenas o username"
            required: false
      - label: "Tema"
        name: "theme"
        file: "src/yml/theme.yml"
        fields:
          - label: "Primary Color"
            name: "primaryColor"
            widget: "color"
            default: "#B73A46"
          - label: "Primary Color Dark"
            name: "primaryColorDark"
            widget: "color"
            default: "#912C36"
          - label: "Primary Color Lighten"
            name: "primaryColorLighten"
            widget: "color"
            default: "#D64654"
          - label: "Primary Color Contrast"
            name: "primaryColorContrast"
            widget: "color"
            default: "#FFFFFF"
          - label: "Secondary Color"
            name: "secondaryColor"
            widget: "color"
            default: "#45D69E"
          - label: "Secondary Color Dark"
            name: "secondaryColorDark"
            widget: "color"
            default: "#176C4B"
          - label: "Secondary Color Lighten"
            name: "secondaryColorLighten"
            widget: "color"
            default: "#5EEDB6"
          - label: "Secondary Color Contrast"
            name: "secondaryColorContrast"
            widget: "color"
            default: "#FFFFFF"
          - label: "Tertiary Color"
            name: "tertiaryColor"
            widget: "color"
            default: "#EFB03A"
          - label: "Tertiary Color Dark"
            name: "tertiaryColorDark"
            widget: "color"
            default: "#CB942F"
          - label: "Tertiary Color Lighten"
            name: "tertiaryColorLighten"
            widget: "color"
            default: "#F2BD5B"
          - label: "Tertiary Color Contrast"
            name: "tertiaryColorContrast"
            widget: "color"
            default: "#FFFFFF"
          - label: "Medium Color"
            name: "mediumColor"
            widget: "color"
            default: "#626262"
          - label: "Medium Color Dark"
            name: "mediumColorDark"
            widget: "color"
            default: "#3E3E3E"
          - label: "Medium Color Lighten"
            name: "mediumColorLighten"
            widget: "color"
            default: "#DADADB"
          - label: "Medium Color Contrast"
            name: "mediumColorContrast"
            widget: "color"
            default: "#FFFFFF"
          - label: "Light Color"
            name: "lightColor"
            widget: "color"
            default: "#F8F8F8"
          - label: "Light Color Dark"
            name: "lightColorDark"
            widget: "color"
            default: "#D7D8DA"
          - label: "Light Color Lighten"
            name: "lightColorLighten"
            widget: "color"
            default: "#F5F6F9"
          - label: "Light Color Contrast"
            name: "lightColorContrast"
            widget: "color"
            default: "#000000"
      - label: "Posts"
        name: "posts"
        file: "src/yml/posts.yml"
        fields:
          - label: "Mostrar modal na saída"
            name: "show_modal_on_exit"
            widget: "boolean"
            default: false
      - label: "Avançado"
        name: "advanced"
        file: "src/yml/advanced.yml"
        fields:
          - label: "URL Base"
            name: "baseurl"
            widget: "string"
            hint: "O subcaminho do seu site, por exemplo /blog"
          - label: "URL"
            name: "url"
            widget: "string"
            hint: "O nome do host e o protocolo base do seu site, por exemplo https://idvogados.github.io"
          - label: "Google Analytics ID"
            name: "google_analytics"
            widget: "string"
            required: false
          - label: "Language"
            name: "language"
            widget: "string"
            hint: "Idioma do conteúdo, ex: pt-BR, en, fr"
          - label: "Pasta Categorias"
            name: "categories_folder"
            widget: "string"
            hint: "Pasta onde estão todas as páginas de categorias. Ex: category"
            required: false
